// components/ChatMessage.vue
<template>
  <div>
    <!-- System Message -->
    <div v-if="message.sender === 'system'" class="text-center my-6">
      <div class="inline-flex items-center gap-2 bg-gradient-to-r from-cyan-500/20 to-blue-500/20 backdrop-blur-sm rounded-full px-6 py-2 border border-cyan-300/30">
        <div class="w-2 h-2 bg-cyan-400 rounded-full animate-pulse"></div>
        <p class="text-sm text-cyan-100 font-medium">{{ message.text }}</p>
      </div>
    </div>

    <!-- User/Bot Message -->
    <div v-else :class="['flex items-start gap-4 my-6', isBot ? 'justify-start' : 'justify-end']">
      <!-- Bot Avatar -->
      <div v-if="isBot" class="flex-shrink-0 w-12 h-12 rounded-full bg-gradient-to-br from-cyan-400 to-blue-500 flex items-center justify-center shadow-lg ring-2 ring-white/20">
        <svg class="w-6 h-6 text-white" viewBox="0 0 20 20" fill="currentColor">
          <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z"/>
        </svg>
      </div>

      <!-- Message Bubble -->
      <div :class="[
        'max-w-xs md:max-w-md lg:max-w-lg px-5 py-4 rounded-2xl shadow-xl',
        isBot
          ? 'bg-white/90 backdrop-blur-sm text-gray-800 rounded-tl-none border border-cyan-200/50'
          : 'bg-gradient-to-br from-orange-400 to-pink-500 text-white rounded-br-none'
      ]">
        <p class="text-sm leading-relaxed">{{ message.text }}</p>

        <!-- Link Button -->
        <a
          v-if="message.link"
          :href="message.link.url"
          target="_blank"
          rel="noopener noreferrer"
          class="mt-4 flex items-center justify-center gap-2 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-600 hover:to-blue-700 text-white font-semibold py-3 px-5 rounded-xl text-sm transition-all duration-300 shadow-lg transform hover:scale-105 hover:shadow-xl"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6" />
          </svg>
          {{ message.link.text }}
        </a>
      </div>

      <!-- User Avatar -->
      <div v-if="!isBot" class="flex-shrink-0 w-12 h-12 rounded-full bg-gradient-to-br from-orange-400 to-pink-500 flex items-center justify-center shadow-lg ring-2 ring-white/20">
        <svg class="w-6 h-6 text-white" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd" />
        </svg>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ChatMessage as ChatMessageType } from '../types'

interface Props {
  message: ChatMessageType
}

const props = defineProps<Props>()

const isBot = computed(() => props.message.sender === 'bot')
</script>

<style scoped>
/* Add smooth animations */
.flex {
  animation: fadeInUp 0.4s ease-out;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>

// components/ChatMessage.tsx
import React from 'react';
import type { ChatMessage as ChatMessageType } from '../types';

interface ChatMessageProps {
  message: ChatMessageType;
}

const BotIcon = () => (
  <svg
    className="w-8 h-8 text-white"
    viewBox="0 0 24 24"
    fill="currentColor"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zM8.5 13.5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm7 0c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm-3.88 3.5c-2.33 0-4.31-1.46-5.11-3.5h10.22c-.8 2.04-2.78 3.5-5.11 3.5z"
    />
  </svg>
);

const UserIcon = () => (
  <svg
    className="w-8 h-8 text-white"
    viewBox="0 0 24 24"
    fill="currentColor"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"
    />
  </svg>
);

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isBot = message.sender === 'bot';
  
  if (message.sender === 'system') {
    return (
       <div className="text-center my-4">
          <p className="text-sm text-gray-400 bg-gray-700/50 rounded-full px-4 py-1 inline-block">{message.text}</p>
       </div>
    )
  }

  return (
    <div className={`flex items-start gap-3 my-4 ${isBot ? 'justify-start' : 'justify-end'}`}>
      {isBot && (
        <div className="flex-shrink-0 w-10 h-10 rounded-full bg-cyan-500 flex items-center justify-center">
          <BotIcon />
        </div>
      )}
      <div
        className={`max-w-xs md:max-w-md lg:max-w-lg px-4 py-3 rounded-2xl shadow-md ${
          isBot
            ? 'bg-gray-700 text-white rounded-tl-none'
            : 'bg-blue-600 text-white rounded-br-none'
        }`}
      >
        <p className="text-sm">{message.text}</p>
        {message.link && (
            <a
                href={message.link.url}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-3 inline-block bg-cyan-500 hover:bg-cyan-600 text-white font-bold py-2 px-4 rounded-lg text-sm transition-colors duration-300 w-full text-center"
            >
                {message.link.text}
            </a>
        )}
      </div>
       {!isBot && (
        <div className="flex-shrink-0 w-10 h-10 rounded-full bg-indigo-500 flex items-center justify-center">
          <UserIcon />
        </div>
      )}
    </div>
  );
};

export default ChatMessage;
